Criar comando !jobs
devpt-org/discord-bot pull request #46
Opened 2022-09-15 00:28 UTC by NightmareR1

> Este comando torna o canal de Classificados fechado.

> Quando um utilizador o chama, são pedidas varias informações em prompt que irão obrigar uma estrutura fixa de ofertas de trabalho, sendo assim essas opções obrigatórias/opcionais

> Após o utilizador enviar esse comando serão criadas as threads para discussão do mesmo e o comando será removido do chat que foi chamado.

2022-09-15 06:50 UTC, IvoPereira requested changes

2022-09-15 06:50 UTC, IvoPereira commented on .vs/VSWorkspaceState.json
> +}
Penso que todos os ficheiros dentro da pasta .vs tenham sido enviados por engano. Consegues removê-los?

2022-09-15 06:54 UTC, IvoPereira commented
Gosto bastante do conceito deste issue, mas diria para esperarmos para darmos merge de um issue que dê suporte a ES6 (#40 ou #44) para deixarmos as Promises um pouco mais limpas com awaits/asyncs.

Até para conseguirmos criar testes porque este envolve uma dinâmica mais complexa.

2022-10-03 12:14 UTC, IvoPereira requested changes

2022-10-03 12:14 UTC, IvoPereira commented on application/usecases/createJobUseCase.ts
> +      this.messageRepository.getJobQuestions(),
Tem demasiadas responsabilidades também. Se o objetivo dele é criar um embed de key (jobQuestion) + resposta, diria que não devemos misturar os dois.

Sugeria usarmos o [Builder Pattern](https://refactoring.guru/design-patterns/builder) e criar um EmbedBuilder.

Basicamente, aqui depois poderias fazer algo do género:
```ts
const embed: Embed = new EmbedBuilder()
    .withAuthor(new Author('username'))
    .withReactions("👍", "👎")
    .withTitle('Test')
    .withFields(
        new EmbedField('key-1', 'value-1'),
        new EmbedField('key-1', 'value-2'),
    )
    .build();
```

O próprio Discord tem um já (`new MessageEmbed()`), que é só deles, poderíamos criar um novo como ilustrei acima.

2022-10-03 12:14 UTC, IvoPereira commented on infrastructure/service/discordChatService.ts
> +    const author = (await guild.members.fetch(user.id)).user;
Talvez possamos ir buscar o user diretamente sem usar as guilds, e assim nem precisamos de passar o guildId para aqui?

https://stackoverflow.com/a/65980351

Quando menos coisas específicas de implementações usarmos melhor, porque senão isto pode trazer-nos problemas caso queiramos usar outra implementação que não Discord e pode a obrigar-nos a mudar um pouco a arquitetura.

2022-10-03 12:14 UTC, IvoPereira commented on infrastructure/service/discordChatService.ts
> +    }
Porque não passar diretamente o `channel` para a função e evitávamos uma outra verificação (tendo em conta que se temos uma instância válida de um Canal, é porque este já foi validado)?

2022-10-03 12:14 UTC, IvoPereira commented on infrastructure/service/discordChatService.ts
> +      });
Deixei umas notas sobre isto mais acima. Sugeria usarmos um Builder nosso que criava o Builder do Discord. Assim consegues ter flexibilidade no Use Case para criares objetos de domínio, e opcionais caso necessites.

2022-10-05 15:39 UTC, C0ffeeL0ver commented on application/usecases/createJobUseCase.ts
> +    }
o type do discord faz com que o guild obtido através da mensagem possa ser indefinido

2023-02-21 10:52 UTC, IvoPereira commented
@NightmareR1 ainda planeias continuar com este MR?

2025-02-21 22:12 UTC, IvoPereira commented
Tendo em conta a inatividade no PR, vou optar por fechar (até porque provavelmente as bibliotecas já sofreram atualizações que deveríamos ter em conta).

2025-02-21 22:12 UTC, closed without merging