Adicionar Leaderboard do CodeWars
devpt-org/discord-bot pull request #53
Opened 2022-09-30 21:31 UTC by IvoPereira

Este PR implementa a listagem dos participantes do CodeWars devPT.

Este UseCase é invocado através do comando **!cwl**.

- Caso não existam participantes, é mostrada uma mensagem a informar que não existem participantes.
- Caso existam até 10 participantes, são mostrados numa lista os existentes.
- Caso passem os 10 participantes, serão mostrados numa lista os existentes e mostrado então o número dos restantes e um link onde o leaderboard pode ser visto de forma completa.

2022-10-08 00:09 UTC, gustavos00 requested changes

2022-10-08 00:09 UTC, gustavos00 commented on application/usecases/sendCodewarsLeaderboardToChannel/sendCodewarsLeaderboardToChannelUseCase.ts
> +  constructor({ chatService, kataService }: { chatService: ChatService; kataService: KataService }) {
Como falamos, deveriamos ter o `constructor` primeiro :)

2022-10-08 00:09 UTC, gustavos00 commented on infrastructure/service/codewarsKataService.ts
> +  private baseUrl = "https://codewars.devpt.co";
Por mera logica, há algum problema em esta variavel ser `protected`?

2022-10-22 19:27 UTC, IvoPereira commented on infrastructure/service/codewarsKataService.ts
> +  private baseUrl = "https://codewars.devpt.co";
Não espero que a classe do Service seja herdada de todo, até porque a mudar algo preferia composição ao invés de herança.

Terias outra ideia para aqui?

2022-10-23 07:25 UTC, IvoPereira commented on infrastructure/service/codewarsKataService.ts
> +  private baseUrl = "https://codewars.devpt.co";
Como referido no Discord, para não atrasar mais a necessidade de implementação desta funcionalidade vou já dar merge.

Se achares necessário podemos depois abrir um novo PR para alterar algo.

2022-10-23 07:25 UTC, merged