Handle roles
devpt-org/discord-bot pull request #56
Opened 2022-10-13 20:57 UTC by Adjilino

**Controlo de permissões/roles por reações**
Permitir atribuir permissões/roles através de reações de mensagens existentes

**Error conhecidos**
- Remover emoji só funciona se a reação for adicionada depois de bot estar online

**Melhorias a fazer**
- Remover consoles
- Se canal não for encontrado não "crashar" e só dar log (abortar listener)

2022-10-24 18:40 UTC, IvoPereira commented
Para que fique de nota, este PR foi discutido no Discord e falta implementar ainda uma eventual migração de acordo com a arquitetura atual + testes.

https://github.com/devpt-org/discord-bot/pull/57/files

2023-01-06 13:59 UTC, Adjilino commented
@IvoPereira encontrei um exemplo no discord Tesla, o que ação de esta solução?

![image](https://user-images.githubusercontent.com/38920989/211026800-3309e002-70d9-4098-9b0c-16068a40a18f.png)

2023-01-10 22:34 UTC, Adjilino commented
Só falta a ver se consigo implementar os emoji's

2023-01-13 22:35 UTC, Adjilino commented
@IvoPereira It's ready, finalmente

2023-01-21 12:36 UTC, Adjilino reviewed
@IvoPereira está pronto, consegues dar uma vista de olhos e verificar os pontos que coloquei

2023-01-21 12:36 UTC, Adjilino commented on application/usecases/selectRoleDropdownUseCase.ts
> +  }
@IvoPereira verifica se estes statics que coloquei para ajudar na implementação de tests estão no local esperado

2023-01-21 12:36 UTC, Adjilino commented on domain/service/chatService.ts
> +  sendInteractionReply(interaction: any, message: string | CustomMessage): Promise<void>;
@IvoPereira passar só a função de interaction não funciona 😢 utilizei o any 😑

2023-02-21 10:25 UTC, IvoPereira requested changes
Enviei algumas notas principalmente referentes a abstração de tipos.

Senão concordares com alguma coisa ou quiseres discutir alguma abordagem pinga-me no Discord.

Excelente trabalho  :+1: face à versão anterior há uma diferença gigante!

2023-02-21 10:25 UTC, IvoPereira commented on application/usecases/confirmRemoveRoleDropdownUseCase.ts
> +  }
Diria que nem tudo o que aqui está pode dar exceção.

Consegues encapsular apenas o que possa dar exceção dentro do try/catch?

E para os logs talvez queiras usar o `loggerService`, vê o `sendWelcomeMessageUseCase`.

2023-02-21 10:25 UTC, IvoPereira commented on application/usecases/confirmRemoveRoleDropdownUseCase.ts
> +  async execute(interaction: ButtonInteraction<CacheType>) {
Conseguimos abstrair este type do Discord.js? A ideia seria não usarmos as implementações específicas (Discord neste caso) nos usecases.

2023-02-21 10:25 UTC, IvoPereira commented on application/usecases/confirmRemoveRoleDropdownUseCase.ts
> +      this.chatService.removeUserRole(interaction.guildId, interaction.user.id, roleId);
Através do user não conseguimos ir buscar o guild? Assim passaríamos apenas um ID e um Role (o que seria mais fácil de aplicar a outros serviços - Slack, etc)

2023-02-21 10:25 UTC, IvoPereira commented on application/usecases/selectRoleDropdownUseCase.ts
> +import { ActionRowBuilder, ButtonBuilder, ButtonStyle, CacheType, StringSelectMenuInteraction } from "discord.js";
Estes types seria interessante conseguirmos abstraí-los também. Achas que conseguimos?

2023-02-21 10:25 UTC, IvoPereira commented on application/usecases/selectRoleDropdownUseCase.ts
> +      ]);
As mesmas sugestões que fiz acima de tentarmos ir buscar a guild através do user id (dentro do chatService).

2023-02-21 10:25 UTC, IvoPereira commented on application/usecases/selectRoleDropdownUseCase.ts
> +          SelectRoleDropdownUseCase.confirmRemoveRoleMessage(selectedRoleMap.id, selectedRoleMap.name)
Penso que possas tirar a função de estática e chamar a própria instância?

```suggestion
          this.sendMessageConfirmRemoveRole(selectedRoleMap.id, selectedRoleMap.name)
```

2023-02-21 10:25 UTC, IvoPereira commented on application/usecases/selectRoleDropdownUseCase.ts
> +          SelectRoleDropdownUseCase.addedRoleMessage(selectedRoleMap.name)
O mesmo aqui?

```suggestion
          this.sendMessageAddedRole(selectedRoleMap.name)
```

2023-02-21 10:25 UTC, IvoPereira commented on application/usecases/selectRoleDropdownUseCase.ts
> +      console.error(error);
Aqui podemos também utilizar o `LoggerService`.

2023-02-21 10:25 UTC, IvoPereira commented on application/usecases/sendRolesDropdownMessage/sendRolesDropdownMessageUseCase.ts
> +    }
Nem tudo isto precisa de estar dentro do try/catch. Podemos simplificar e dar wrap só do que pode dar exceção.

2023-02-21 10:25 UTC, IvoPereira commented on application/usecases/sendRolesDropdownMessage/sendRolesDropdownMessageUseCase.ts
> +      if (!guildId || !memberId) return;
Existe alguma situação onde podemos não estar a receber algum destes valores?

2023-02-21 10:25 UTC, IvoPereira commented on application/usecases/sendRolesDropdownMessage/sendRolesDropdownMessageUseCase.ts
> +      });
Temo que este `forEach` com os `await` possam não estar a fazer o que queres, pelo menos pela ordem certa. Ao invocares como invocaste aqui ele não respeita a ordem e faz-te diversas chamadas assíncronas para o envio de mensagens.

[O `for...const` penso que te ajude aqui](https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop).

2023-02-21 10:25 UTC, IvoPereira commented on application/usecases/sendRolesDropdownMessage/sendRolesDropdownMessageUseCase.ts
> +      OPTIONS: RoleInterface[];
Esta variável está em maiúsculas por alguma razão em particular?

2023-02-21 10:25 UTC, IvoPereira commented on domain/service/interactionCreateUseCaseResolver.ts
> +import { CacheType, Interaction } from "discord.js";
Podemos abstrair estes tipos?

2023-02-21 10:25 UTC, IvoPereira commented on vitest/application/usecases/sendRolesDropdownMessageUseCase.spec.ts
> +  // };
Podemos remover este comment?

2023-02-23 21:49 UTC, Adjilino commented on application/usecases/confirmRemoveRoleDropdownUseCase.ts
> +      this.chatService.removeUserRole(interaction.guildId, interaction.user.id, roleId);
Infelizmente a interaction não traz o id de member que é relação de user com guild

2023-02-23 22:08 UTC, Adjilino commented on application/usecases/confirmRemoveRoleDropdownUseCase.ts
> +  }
Acho que é só estes 2 serviços

2023-02-23 22:09 UTC, Adjilino commented on application/usecases/confirmRemoveRoleDropdownUseCase.ts
> +  async execute(interaction: ButtonInteraction<CacheType>) {
Não encontrei nenhuma maneira de conseguir obter interaction por id

2023-02-23 22:10 UTC, Adjilino commented on application/usecases/selectRoleDropdownUseCase.ts
> +      console.error(error);
Feito

2023-02-23 22:11 UTC, Adjilino commented on application/usecases/confirmRemoveRoleDropdownUseCase.ts
> +  }
removeUserRole

2023-02-23 22:19 UTC, Adjilino commented on application/usecases/selectRoleDropdownUseCase.ts
> +          SelectRoleDropdownUseCase.confirmRemoveRoleMessage(selectedRoleMap.id, selectedRoleMap.name)
A função estática serviu para ajudar a construir a mesagem para os testes

2023-02-23 22:19 UTC, Adjilino commented on application/usecases/selectRoleDropdownUseCase.ts
> +          SelectRoleDropdownUseCase.addedRoleMessage(selectedRoleMap.name)
A função estática serviu para ajudar a construir a mesagem para os testes

2023-03-01 21:54 UTC, Adjilino commented on application/usecases/sendRolesDropdownMessage/sendRolesDropdownMessageUseCase.ts
> +      if (!guildId || !memberId) return;
Nunca aconteceu, mas os types vêm string | null

2023-05-30 11:19 UTC, closed without merging